import 'dart:io';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/auth_provider.dart';
import '../../providers/post_provider.dart';
import '../../../core/utils/image_picker_helper.dart';
import '../../../data/services/firebase_storage_service.dart';
import '../../../data/models/post_model.dart';
import '../../../core/constants/app_constants.dart';

class LeaderCreatePostScreen extends StatefulWidget {
  const LeaderCreatePostScreen({super.key});

  @override
  State<LeaderCreatePostScreen> createState() => _LeaderCreatePostScreenState();
}

class _LeaderCreatePostScreenState extends State<LeaderCreatePostScreen> {
  final _formKey = GlobalKey<FormState>();
  final _textController = TextEditingController();
  File? _selectedImage;
  bool _isUploading = false;

  @override
  void dispose() {
    _textController.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    final image = await ImagePickerHelper.pickImage();
    if (image != null) {
      setState(() {
        _selectedImage = image;
      });
    }
  }

  Future<void> _createPost() async {
    if (!_formKey.currentState!.validate()) return;
    if (_textController.text.trim().isEmpty && _selectedImage == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please add text or an image')),
      );
      return;
    }

    setState(() {
      _isUploading = true;
    });

    try {
      final authProvider = context.read<AuthProvider>();
      final user = authProvider.currentUserEntity;
      final userId = authProvider.currentUser?.uid;

      if (user == null || userId == null) {
        throw Exception('User not found');
      }

      String? imageUrl;

      if (_selectedImage != null) {
        final storageService = FirebaseStorageService();
        imageUrl = await storageService.uploadPostImage(
          DateTime.now().millisecondsSinceEpoch.toString(),
          _selectedImage!,
        );
      }

      final post = PostModel(
        id: '', // Will be generated by Firestore
        leaderId: userId,
        leaderName: user.name,
        leaderProfileImageUrl: user.profileImageUrl,
        text: _textController.text.trim(),
        imageUrl: imageUrl,
        likesCount: 0,
        createdAt: DateTime.now(),
      );

      final postProvider = context.read<PostProvider>();
      final success = await postProvider.createPost(post);

      if (!mounted) return;

      if (success) {
        Navigator.of(context).pop();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Post created successfully')),
        );
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(postProvider.error ?? 'Failed to create post')),
        );
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error: $e')),
      );
    } finally {
      if (mounted) {
        setState(() {
          _isUploading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Post'),
        actions: [
          if (_isUploading)
            const Padding(
              padding: EdgeInsets.all(16),
              child: SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(strokeWidth: 2),
              ),
            )
          else
            TextButton(
              onPressed: _createPost,
              child: const Text('Post'),
            ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              TextFormField(
                controller: _textController,
                maxLines: 8,
                maxLength: AppConstants.maxPostTextLength,
                decoration: const InputDecoration(
                  hintText: 'What would you like to share?',
                  border: OutlineInputBorder(),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    if (_selectedImage == null) {
                      return 'Please add text or an image';
                    }
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),
              if (_selectedImage != null) ...[
                Stack(
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.circular(12),
                      child: Image.file(
                        _selectedImage!,
                        width: double.infinity,
                        fit: BoxFit.cover,
                      ),
                    ),
                    Positioned(
                      top: 8,
                      right: 8,
                      child: IconButton(
                        icon: const Icon(Icons.close, color: Colors.white),
                        style: IconButton.styleFrom(
                          backgroundColor: Colors.black54,
                        ),
                        onPressed: () {
                          setState(() {
                            _selectedImage = null;
                          });
                        },
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 16),
              ],
              OutlinedButton.icon(
                onPressed: _pickImage,
                icon: const Icon(Icons.image),
                label: const Text('Add Image'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
